service: project-generator-server


provider:
  name: aws
  runtime: java8
  
package:
  artifact: build/distributions/project-generator-server.zip

functions:
  Donut:
    handler: LambdaHandler
    events:
      - http:
          path: Donut
          method: get
